version: 2.1

orbs:
  node: circleci/node@5

jobs:
  lint_code:
    executor:
      name: node/default
      tag: '18'  # Specify the Node.js version here
    description: Lint code
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Lint code
          command: npm run lint:fix

  run_tests:
    executor:
      name: node/default
      tag: '18'  # Specify the Node.js version here
    description: Run tests
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm run test

  build:
    executor:
      name: node/default
      tag: '18'  # Specify the Node.js version here
    description: Build
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build
          command: npm run build

workflows:
  build_app:
    jobs:
      - lint_code
      - run_tests
      - build