version: 2.1

orbs:
  node: circleci/node@5

jobs:
  lint_code:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          override-ci-command: npm ci --legacy-peer-deps
      - run:
          name: Lint code
          command: npm run lint:fix

  run_tests:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          override-ci-command: npm ci --legacy-peer-deps
      - run:
          name: Run tests
          command: npm run test

  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          override-ci-command: npm ci --legacy-peer-deps
      - run:
          name: Build
          command: npm run build

workflows:
  build_app:
    jobs:
      - lint_code
      - run_tests:
          requires:
            - lint_code
      - build:
          requires:
            - run_tests