version: 2.1

orbs:
  node: circleci/node@5

jobs:
  lint_code:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          cache-path: ~/project/node_modules
          cache-version: v1
          override-ci-command: npm ci
      - run:
          name: Lint code
          command: npm run lint:fix

  run_tests:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          cache-path: ~/project/node_modules
          cache-version: v1
          override-ci-command: npm ci
      - run:
          name: Run tests
          command: npm run test

  build:
    docker:
      - image: cimg/node:20.17.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          cache-path: ~/project/node_modules
          cache-version: v1
          override-ci-command: npm ci
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  run_release:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          cache-path: ~/project/node_modules
          cache-version: v1
          override-ci-command: npm ci
      - run:
          name: Set up git credentials
          command: | 
            git config --global user.email $GIT_USER_EMAIL
            git config --global user.name $GIT_USER_NAME
      - run:
          name: Run release
          command: npm run release
  
  publish_to_npm:
  executor: node/default  
  environment:
    NPM_TOKEN: $NPM_TOKEN
  steps:
    - checkout
    - node/install-packages:
        pkg-manager: npm
        cache-path: ~/project/node_modules
        cache-version: v1
        override-ci-command: npm ci
    - run: 
        name: login to npm 
        command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
    - run:
        name: Publish to NPM
        command: npm run publish


workflows:
  build_app:
    jobs:
      - lint_code
      - run_tests:
          requires:
            - lint_code
      - build:
          requires:
            - run_tests
      - run_release:
          requires:
            - build
      - publish_to_npm:
          requires:
            - run_release