version: 2.1

orbs:
  node: circleci/node@5

jobs:
  lint_code:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          cache-path: ~/project/node_modules
          cache-version: v1
          override-ci-command: npm ci
      - run:
          name: Lint code
          command: npm run lint:fix

  run_tests:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          cache-path: ~/project/node_modules
          cache-version: v1
          override-ci-command: npm ci
      - run:
          name: Run tests
          command: npm run test

  build:
    docker:
      - image: cimg/node:20.17.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          cache-path: ~/project/node_modules
          cache-version: v1
          override-ci-command: npm ci
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  publish_to_npm:
    docker:
      - image: cimg/node:20.17.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - node/install-packages:
          pkg-manager: npm
          cache-version: v1
          override-ci-command: npm ci
      - run:
          name: Authenticate with npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Publish to npm
          command: npm publish --access public

workflows:
  version: 2
  build_and_publish:
    jobs:
      - lint_code
      - run_tests:
          requires:
            - lint_code
      - build:
          requires:
            - run_tests
      - publish_to_npm:
          requires:
            - build
          filters:
            branches:
              only: main
